export default [
  {
    id: 'cn',
    name: '中文',
    btnIsShowA: '包括A女神',
    btnRandom: '老虎機',
    randomFirst: 'ROLL先後',
    first: '先手',
    second: '後手',
    btnRandomItem: '抽取',
    lock: '鎖定',
    lockCancel: '解除鎖定',
    stop: '停止',
    toGroup: '構築',
    cancel: '取消選擇',
    btnCheck: '查看已選',
    btnShare: '分享你的卡組',
    btnReturn: '返回',
    copyright: '本網頁使用的圖像素材來自於ふるよにコモンズ。\nふるよにコモンズ/BakaFire,TOKIAME\n版權歸以上公司所有',
    cardCost: '氣',
    cardOpen: '開傘：',
    cardClose: '閉傘：',
    cardRange: '距離',
    cardCapacity: '納',
    cardCapacityGrowup: '生',
    typeAttack: '攻擊',
    typeAction: '行動',
    typeReaction: '對應',
    typeFullpower: '全力',
    typeEnhance: '付與',
    typeVariable: '不定',
    typeShortAttack: '攻',
    typeShortAction: '行',
    typeShortReaction: '對',
    typeShortFullpower: '全',
    typeShortEnhance: '付',
    btn2Pick: '2Pick構築',
    groupTips: '選擇7張通常和3張切即可分享構築',
    changeGroupTypeText: '切換組卡界面',
    changeAreaText: '指定範圍抽取',
    verBasic: '基礎',
    verPro: '達人',
    ver1: '壹',
    ver2: '貳',
    ver3: '叄',
    ver4: '肆',
    ver5: '伍',
    ver6: '陸',
    changeLog: '更新日誌'
  },
  {
    id: 'jp',
    name: '日本語',
    btnIsShowA: 'アナザーメガミ含み',
    btnRandom: 'スロットマシン式',
    randomFirst: '先手後手',
    first: '先',
    second: '後',
    btnRandomItem: 'ランダム',
    lock: 'ロック',
    lockCancel: 'ロック解除',
    stop: 'ストップ',
    toGroup: 'デッキ構築',
    cancel: 'キャンセル',
    btnCheck: 'カード詳細',
    btnShare: '構築をシェアする',
    btnReturn: '戻る',
    copyright: '本ページはふるよにコモンズの画像を使用しています。\nふるよにコモンズ/BakaFire,TOKIAME',
    cardCost: 'フレア',
    cardOpen: '開；',
    cardClose: '閉；',
    cardRange: '距離',
    cardCapacity: '納',
    cardCapacityGrowup: '生',
    typeAttack: '攻撃',
    typeAction: '行動',
    typeReaction: '対応',
    typeFullpower: '全力',
    typeEnhance: '付与',
    typeVariable: '不定',
    typeShortAttack: '攻',
    typeShortAction: '行',
    typeShortReaction: '対',
    typeShortFullpower: '全',
    typeShortEnhance: '付',
    btn2Pick: '2Pick構築シミュレーター',
    groupTips: '通常札計7枚、切り札計3枚を選択すれば、\n構築をシェアすることができます',
    changeGroupTypeText: '表示方法変更',
    changeAreaText: 'ランダム範囲指定',
    verBasic: '基本',
    verPro: '達人',
    ver1: '壱',
    ver2: '弐',
    ver3: '参',
    ver4: '四',
    ver5: '伍',
    ver6: '六',
    changeLog: '更新履歴'
  },
  {
    id: 'kr',
    name: '한국어',
    btnIsShowA: '어나더 여신 포함',
    btnRandom: '슬롯 머신 모드',
    randomFirst: '선공 후공',
    first: '선공',
    second: '후공',
    btnRandomItem: '랜덤',
    lock: '잠금',
    lockCancel: '잠금 해제',
    stop: '스톱',
    toGroup: '덱구축',
    cancel: '취소',
    btnCheck: '카드 상세',
    btnShare: '구축을 공유한다',
    btnReturn: '돌아가기',
    copyright: '본 사이트는 ふるよにコモンズ의 이미지를 사용하고 있습니다.\nふるよにコモンズ/BakaFire,TOKIAME',
    cardCost: '플레어',
    cardOpen: '펼침；',
    cardClose: '닫힘；',
    cardRange: '거리',
    cardCapacity: '납',
    typeAttack: '공격',
    typeAction: '행동',
    typeReaction: '대응',
    typeFullpower: '전력',
    typeEnhance: '부여',
    typeVariable: '부정',
    typeShortAttack: '공',
    typeShortAction: '행',
    typeShortReaction: '대',
    typeShortFullpower: '전',
    typeShortEnhance: '부',
    btn2Pick: '2pick 구축 시뮬레이터',
    groupTips: ''
  },
  {
    id: 'en',
    name: 'ENGLISH',
    btnIsShowA: 'Another Megamis Included',
    btnRandom: 'Animation On',
    randomFirst: 'Pick Starting Player',
    first: 'You',
    second: 'Opponent',
    btnRandomItem: 'Randomly Pick',
    lock: 'Locked:',
    lockCancel: 'Unlock',
    stop: 'Stop',
    toGroup: 'Go to Deck-Building Panel',
    cancel: 'Deselect All',
    btnCheck: 'Deck Overview',
    btnShare: 'Share As URL',
    btnReturn: 'Return',
    copyright: 'Assets used in this page are from Furuyoni Commons.\nふるよにコモンズ/BakaFire,TOKIAME\nAll Rights Reserved.',
    cardCost: 'Flare Cost',
    cardOpen: 'Open：',
    cardClose: 'Closed：',
    cardRange: 'Range',
    cardCapacity: '',//Charge
    typeAttack: 'Attack',
    typeAction: 'Action',
    typeReaction: 'Reaction',
    typeFullpower: 'Throughout',
    typeEnhance: 'Enhancement',
    typeVariable: 'Undefined',
    typeShortAttack: 'ATK',
    typeShortAction: 'ACT',
    typeShortReaction: 'REA',
    typeShortFullpower: 'THR',
    typeShortEnhance: 'ENH',
    btn2Pick: 'Pick 2 and Build a Deck',
    groupTips: '',
    changeLog: 'Change Log'
  }
]